---
title: "final-edav-project"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(extracat)
library(dplyr)
library(tidyverse)
```

# Race segregation in NYC schools by Boroughs

```{r}
school_seg_123 = read.csv2("https://data.cityofnewyork.us/Education/2013-2018-Demographic-Snapshot-School/s52a-8aq6/2013_-_2018_Demographic_Snapshot_School.csv", header=TRUE, sep=",")

```

```{r}
#extract the Borough names from DBN mame parterns

school_seg$Borough <-  
  ifelse((substr(school_seg$DBN, 3,3) == "M"), "MANHATTAN",
         ifelse((substr(school_seg$DBN, 3,3) == "X"), "BRONX",
                ifelse((substr(school_seg$DBN, 3,3) == "K"), "BROOKLYN",
                       ifelse((substr(school_seg$DBN, 3,3) == "Q"), "QUEENS",
                              ifelse(substr(school_seg$DBN, 3,3) == "R", "STATEN IS", "something else")))))
#data cleaning
school_seg$X..Asian <- as.numeric(school_seg$X..Asian)
school_seg$X..Black <- as.numeric(school_seg$X..Black)
school_seg$X..White<- as.numeric(school_seg$X..White)
school_seg$X..Hispanic <- as.numeric(school_seg$X..Hispanic)
school_seg$X..Multiple.Race.Categories.Not.Represented <- as.numeric(school_seg$X..Multiple.Race.Categories.Not.Represented)


#function 
get_seg_score <- function(row) {
  colname = row["top_race_name"][[1]]
  top_pct = row[[colname]][[1]]
  return((top_pct * 1.25) - 25)
}

#add few columns to df_1
df_1 <- school_seg[,c("Borough","X..Asian", "X..Black", "X..White", "X..Hispanic","X..Multiple.Race.Categories.Not.Represented")]

df_1$top_race <- apply(df_1, 1, which.max)

df_1$top_race_name <- lapply(df_1[,"top_race"], function(x) names(df_1)[x])

df_1$seg_score <- apply(df_1, 1, get_seg_score)

#rename column names 
colnames(df_1) <- c("Borough", "Asian", "Black", "White", "Hispanic", "Multi_race", "Top_race", "Top_race_name", "Segregation_score")

df_2 = df_1 %>%
  group_by(Borough) %>%
  summarise_at(vars(Asian, Black, White, Hispanic, Multi_race), funs(sum)) 

df_2$total <- apply(df_2[,2:6], 1, sum)

df_3 <- df_2 %>%
  mutate_if(is.numeric, funs(./total))

#convert messy to tidy data 
long_df <- df_3 %>% gather(race, race_proportion, Asian:Multi_race)

ggplot(long_df, aes(Borough, race_proportion, fill = race)) + geom_col()


```



######Not used yet ##################3
# Race segregation analysis in NYC schools by zip code

```{r}
school_seg = read.csv2("/Users/meenakshizutshi/Documents/Columbia/edav/final-project/2013_-_2018_Demographic_Snapshot_School.csv", sep=",")
school_location_2018 = read.csv2("/Users/meenakshizutshi/Documents/Columbia/edav/final-project/2018_DOE_High_School_Directory.csv", sep=",")
school_location_2017 = read.csv2("/Users/meenakshizutshi/Documents/Columbia/edav/final-project/2017_DOE_High_School_Directory.csv", sep=",")
school_location_2016 = read.csv2("/Users/meenakshizutshi/Documents/Columbia/edav/final-project/2016_DOE_High_School_Directory.csv", sep=",")
#school_location_2014_2015 = read.csv2("/Users/meenakshizutshi/Documents/Columbia/edav/final-project/2014_-_2015_DOE_High_School_Directory.csv", sep=",")
school_location_2013 = read.csv2("/Users/meenakshizutshi/Documents/Columbia/edav/final-project/DOE_High_School_Directory_2013-2014.csv", sep=",")
```


```{r}
names(school_location_2018)[names(school_location_2018) == "dbn"] <- "DBN"
a <- data.frame(school_location_2018$DBN, school_location_2018$Borough, school_location_2018$Postcode, school_location_2018$Longitude, school_location_2018$Latitude)
#names(a)[names(a) == "school_location_2018.DBN"] <- "DBN"
#names(a)[names(a) == "school_location_2018.Borough"] <- "Borough"
#names(a)[names(a) == "school_location_2018.Postcode"] <- "Postcode"
#names(a)[names(a) == "school_location_2018.Longitude"] <- "Longitude"
#names(a)[names(a) == "school_location_2018.Latitude"] <- "Latitude"

colnames(a) <- c("DBN", "Borough", "Postcode", "Longitude","Latitude")

names(school_location_2017)[names(school_location_2017) == "dbn"] <- "DBN"
b <- data.frame(school_location_2017$DBN, school_location_2017$Borough, school_location_2017$Postcode, school_location_2017$Longitude, school_location_2017$Latitude)
#names(b)[names(b) == "school_location_2017.DBN"] <- "DBN"
#names(b)[names(b) == "school_location_2017.Borough"] <- "Borough"
#names(b)[names(b) == "school_location_2017.Postcode"] <- "Postcode"
#names(b)[names(b) == "school_location_2017.Longitude"] <- "Longitude"
#names(b)[names(b) == "school_location_2017.Latitude"] <- "Latitude"

colnames(b) <- c("DBN", "Borough", "Postcode", "Longitude","Latitude")

names(school_location_2016)[names(school_location_2016) == "dbn"] <- "DBN"
c <- data.frame(school_location_2016$DBN, school_location_2016$borough, school_location_2016$Postcode, school_location_2016$Longitude, school_location_2016$Latitude)
names(c)[names(c) == "school_location_2016.DBN"] <- "DBN"
names(c)[names(c) == "school_location_2016.borough"] <- "Borough"
names(c)[names(c) == "school_location_2016.Postcode"] <- "Postcode"
names(c)[names(c) == "school_location_2016.Longitude"] <- "Longitude"
names(c)[names(c) == "school_location_2016.Latitude"] <- "Latitude"

#names(school_location_2014_2015)[names(school_location_2014_2015) == "dbn"] <- "DBN"
#d <- data.frame(school_location_2014_2015$DBN, school_location_2014_2015$borough, school_location_2014_2015$postcode)
#names(d)[names(d) == "school_location_2014_2015.DBN"] <- "DBN"
#names(d)[names(d) == "school_location_2014_2015.borough"] <- "Borough"
#names(d)[names(d) == "school_location_2014_2015.postcode"] <- "Postcode"

#names(school_location_2013)[names(school_location_2013) == "DBN"] <- "dbn"
e <- data.frame(school_location_2013$DBN, school_location_2013$Borough, school_location_2013$Postcode, school_location_2013$longitude, school_location_2013$latitude)
names(e)[names(e) == "school_location_2013.DBN"] <- "DBN"
names(e)[names(e) == "school_location_2013.Borough"] <- "Borough"
names(e)[names(e) == "school_location_2013.Postcode"] <- "Postcode"
names(e)[names(e) == "school_location_2013.longitude"] <- "Longitude"
names(e)[names(e) == "school_location_2013.latitude"] <- "Latitude"

```


```{r}
all_rows <- bind_rows(a,b,c,e)
all_rows_for_dbn <- distinct(all_rows, DBN, .keep_all= TRUE)
```

```{r}
school_seg_location <- left_join(school_seg, all_rows_for_dbn, by = "DBN")
```



